# Generated by Django 4.0.3 on 2022-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_mes', models.CharField(max_length=255)),
                ('mesimagen', models.CharField(max_length=255)),
                ('mesproceso', models.CharField(max_length=255)),
                ('imagenesprocesadas', models.CharField(max_length=255)),
                ('imagenesaprobadas', models.CharField(max_length=255)),
                ('imagenesborradas', models.CharField(max_length=255)),
                ('cantidausuario', models.CharField(max_length=255)),
                ('promediousuario', models.CharField(max_length=255)),
                ('promedioimagenes', models.CharField(max_length=255)),
                ('porcentajeaprobadas', models.FloatField(max_length=255)),
                ('porcentajeborradas', models.FloatField(max_length=255)),
            ],
        ),
    ]
