# Generated by Django 4.0.3 on 2022-04-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_domicilio_persona_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
